name: Basic CI

# 언제 실행될지 정의 (main 브랜치에 push나 pull_request 발생 시)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # 리눅스 환경에서 실행

    steps:
    # 1. 코드 획득
    - uses: actions/checkout@v4

    # 2. 파이썬 환경 세팅
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # 3. 의존성 패키지 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. pytest 실행
    - name: Run tests with pytest
      run: |
        pytest